### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by saneerayapa** [jeevasusej/react-redux-typescript-starter-kit#1]
Hi 
I m new to react and I need to add firebase authentication 
so, in that case, how do I retrieve username and password from authapi.ts
Thanks

**Comment by jeevasusej** [comment]
why do you want to retrieve from the authapi.ts?

You want to communicate to firebase api with user and password. Right?

If that so, add username and password props to the 
login/containers/loginContainer.tsx
and add properties to the dispatchToProps 

and the related actions also need to be added like adding properties to the actions, api, saga and so on.

Do you expect the same?
Do you want a sample code?

**Comment by dev2-piniada** [comment]
Hi jeewa 

can you able to provide me sample for that no need firebase i need how to pass LoginDetails throughout the api
Thanks

**Comment by saneera** [comment]
can you pleas provide ma an examplle how to userdetails to api

**Comment by jeevasusej** [comment]
Hi,

Sure, I will help you. I will give instructions how to do it.

Thanks & Regards,
Jeeva J

**Comment by jeevasusej** [comment]
- Uninstall axios-mock-adapter. This will block your api calls.
- Check api folder. Here you can add your own api calls and this should be called inside saga. 
For example, 
   return axios.post('/login', {
        username: userdetail.username,
        password: userdetail.password,
    });

**Comment by saneera** [comment]
Thanks 

How do I pass username password in login UI

**Comment by jeevasusej** [comment]
You should dispatch from your component/Containers. 

The flow should be like follow
- Create actions
- Listen actions in Saga (For api calls) / Reducer (to do your logics)
- Call the actions from your Container/Components

Basic Redux - [https://redux.js.org/basics/example](https://redux.js.org/basics/example) 
Saga Basics - [https://redux-saga.js.org/](https://redux-saga.js.org/)
Container and Component - [https://redux.js.org/basics/usage-with-react/](https://redux.js.org/basics/usage-with-react/)

**Comment by saneera** [comment]
Thanks Jeeves

I don’t understand much about react and type script I m learning anyway I will try to do something Thanks again
